roles/docker: support 1.12+ & delete docker.socket
contiv/ansible pull request #307
Opened 2017-01-19 14:19 UTC by unclejack

This PR removes the docker.socket and implements compatibility with Docker 1.12 (or newer). docker.socket has been removed upstream. Compatibility with Docker 1.11 is maintained.

Fixes #301

2017-01-20 12:21 UTC, unclejack commented
ping @gaurav-dalvi

2017-01-20 20:12 UTC, gaurav-dalvi commented
i dont have any comments !
@neelimamukiri may be able to review it !

2017-01-23 20:40 UTC, unclejack commented
@DivyaVavili @neelimamukiri Could you take a look when you have the time to do that, please?

2017-01-23 21:24 UTC, neelimamukiri commented on roles/docker/templates/docker-svc.j2
> +{% set docker_daemon_startup = "docker daemon" %}
Are we supporting the < 1.12 path? If yes, wont we need the docker-tcp tasks from above as well?

2017-01-23 21:32 UTC, unclejack commented on roles/docker/templates/docker-svc.j2
> +{% set docker_daemon_startup = "docker daemon" %}
@neelimamukiri: This was mostly a matter of how the systemd units were set up. They weren't absolutely necessary to run Docker. I've been running Docker for a long time without that setup.

2017-01-23 21:35 UTC, neelimamukiri commented on roles/docker/templates/docker-svc.j2
> +{% set docker_daemon_startup = "docker daemon" %}
Okay, that makes things simpler. Thanks!

2017-01-23 21:35 UTC, neelimamukiri approved these changes

2017-01-23 22:35 UTC, dvavili requested changes

2017-01-23 22:35 UTC, DivyaVavili commented on roles/docker/templates/docker-svc.j2
> +{% set docker_daemon_startup = "docker daemon" %}
@unclejack: docker-tcp.socket is required to enable Docker remote API. docker client can still work without this, but we need to enable remote API for netplugin.

2017-01-23 23:13 UTC, unclejack commented on roles/docker/templates/docker-svc.j2
> +{% set docker_daemon_startup = "docker daemon" %}
@DivyaVavili This is handled by lines 21 and 23 of this template. The UNIX socket and TCP socket options are passed directly to the Docker daemon as options on the command line. The docker-tcp.socket is no longer required.

It doesn't make sense to keep docker-tcp.socket for older versions. Older versions of Docker can also use this setup with `-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock`. This was used to have socket activation and it was more trouble than it was worth. We can just use the latest recommended setup.

I've been using this setup for a long time. I haven't run into any kind of issue so far.

2017-01-24 00:12 UTC, DivyaVavili commented on roles/docker/templates/docker-svc.j2
> +{% set docker_daemon_startup = "docker daemon" %}
OK. Sounds good. The changes LGTM in that case.

2017-01-24 00:12 UTC, dvavili approved these changes

2017-01-24 09:14 UTC, unclejack commented
I'll merge this now. We have two reviews.

2017-01-24 09:15 UTC, merged